baseURL = "https://pcalhaurin.es/"
title = "PCAlhaurín"
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = false

[languages]
  [languages.es]
    languageName = "Español"
    weight = 1
    title = "Reparación de Ordenadores en Alhaurín de la Torre | PCAlhaurín"
  [languages.en]
    languageName = "English"
    weight = 2
    title = "PC Repair in Alhaurín de la Torre | PCAlhaurín"
    languageCode = "en-GB"

[params]
  phone = "+34 614 47 99 22"
  whatsapp = "34614479922"

[outputs]
  home = ["HTML"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5

enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]
