baseURL = "https://pcalhaurin.es/"
title = "PCAlhaurín"
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = false

[languages]
  [languages.es]
    label = "Español"
    locale = "es-ES"
    weight = 1
    title = "Reparación de Ordenadores en Alhaurín de la Torre | PCAlhaurín"
  [languages.en]
    label = "English"
    locale = "en-GB"
    weight = 2
    title = "PC Repair in Alhaurín de la Torre | PCAlhaurín"

[params]
  phone = "+34 614 47 99 22"
  whatsapp = "34614479922"

[outputs]
  home = ["HTML", "RSS"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5

enableRobotsTXT = false
disableKinds = ["taxonomy", "term"]
